import streamlit as st
import pandas as pd
import numpy as np

st.title('Holy crap, I\'m a webpage!')

'''
Block comments like this one appear as plaintext on the webpage.
To run this 'hello, world' script, we do not need the IDE!
All we need to do is to use the streamlit program within the venv and a webpage will
automatically be generated by the data passed in here.

1. Open this file in your IDE of choice.
2. Click on the Terminal (not Python Console!) and make sure you are inside of the venv for the project.
3. type ' streamlit run src/main.py ' and the webpage should appear.
'''

